services:
  postgres_ecommerce:
    image: postgres:latest
    container_name: postgres_ecommerce
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_ecommerce_data:/var/lib/postgresql/data

volumes:
  postgres_ecommerce_data: 