-- Insertar datos de ejemplo para España
INSERT INTO COUNTRIES (CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT 'ES', 'España', 'SYSTEM', 'SYSTEM'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COUNTRIES WHERE CODE = 'ES');

-- Comunidad de Madrid
INSERT INTO AUTONOMOUS_COMMUNITIES (COUNTRY_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT ID, 'MAD', 'Comunidad de Madrid', 'SYSTEM', 'SYSTEM'
FROM COUNTRIES WHERE CODE = 'ES'
AND NOT EXISTS (SELECT 1 FROM AUTONOMOUS_COMMUNITIES WHERE CODE = 'MAD');

-- Provincia de Madrid
INSERT INTO PROVINCES (AUTONOMOUS_COMMUNITY_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT ID, '28', 'Madrid', 'SYSTEM', 'SYSTEM'
FROM AUTONOMOUS_COMMUNITIES WHERE CODE = 'MAD'
AND NOT EXISTS (SELECT 1 FROM PROVINCES WHERE CODE = '28');

-- Municipios de Madrid
INSERT INTO MUNICIPALITIES (PROVINCE_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT p.ID, '28079', 'Madrid', 'SYSTEM', 'SYSTEM'
FROM PROVINCES p WHERE p.CODE = '28'
AND NOT EXISTS (SELECT 1 FROM MUNICIPALITIES WHERE CODE = '28079');

INSERT INTO MUNICIPALITIES (PROVINCE_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT p.ID, '28006', 'Alcalá de Henares', 'SYSTEM', 'SYSTEM'
FROM PROVINCES p WHERE p.CODE = '28'
AND NOT EXISTS (SELECT 1 FROM MUNICIPALITIES WHERE CODE = '28006');

-- Cataluña
INSERT INTO AUTONOMOUS_COMMUNITIES (COUNTRY_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT ID, 'CAT', 'Cataluña', 'SYSTEM', 'SYSTEM'
FROM COUNTRIES WHERE CODE = 'ES'
AND NOT EXISTS (SELECT 1 FROM AUTONOMOUS_COMMUNITIES WHERE CODE = 'CAT');

-- Provincia de Barcelona
INSERT INTO PROVINCES (AUTONOMOUS_COMMUNITY_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT ID, '08', 'Barcelona', 'SYSTEM', 'SYSTEM'
FROM AUTONOMOUS_COMMUNITIES WHERE CODE = 'CAT'
AND NOT EXISTS (SELECT 1 FROM PROVINCES WHERE CODE = '08');

-- Municipios de Barcelona
INSERT INTO MUNICIPALITIES (PROVINCE_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT p.ID, '08019', 'Barcelona', 'SYSTEM', 'SYSTEM'
FROM PROVINCES p WHERE p.CODE = '08'
AND NOT EXISTS (SELECT 1 FROM MUNICIPALITIES WHERE CODE = '08019');

INSERT INTO MUNICIPALITIES (PROVINCE_ID, CODE, NAME, CREATED_BY, UPDATED_BY)
SELECT p.ID, '08101', 'Hospitalet de Llobregat', 'SYSTEM', 'SYSTEM'
FROM PROVINCES p WHERE p.CODE = '08'
AND NOT EXISTS (SELECT 1 FROM MUNICIPALITIES WHERE CODE = '08101');

COMMIT;
